CREATE TABLE short_url (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- nullable: id must exist before we can base62-encode it into short_code (see ShortCodeGenerator);
    -- it is always set before the insert transaction commits, so it is never observably null.
    short_code    VARCHAR(20)   NULL,
    long_url      VARCHAR(2048) NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    CONSTRAINT uq_short_url_short_code UNIQUE (short_code)
);
