CREATE TABLE click_event (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url_id  BIGINT       NOT NULL,
    clicked_at    TIMESTAMP    NOT NULL,
    -- capped and nullable by design: both headers are client-supplied and unvalidated, so they
    -- are treated as untrusted display data, not identifiers. No IP address is stored (PII).
    referrer      VARCHAR(512) NULL,
    user_agent    VARCHAR(512) NULL,
    CONSTRAINT fk_click_event_short_url FOREIGN KEY (short_url_id) REFERENCES short_url (id)
);

CREATE INDEX idx_click_event_short_url_time ON click_event (short_url_id, clicked_at);
